package com.niks.main;

public class Example {
  
  public static void main(String[] args){
    String query=  "search index=distapps  earliest=-60m@m "
        + "sourcetype=slipstream logRecordType=sssystem messageType=SERVERSTATS "
        + "| eval instance=case( match(host, \"gumps1-sshare*-chi.ops.sfdc.net\"), \"CHI\","
        + "match(host, \"gumps1-sshare.*-was.ops.sfdc.net\"), \"CHI-DR\", "
        + "match(host, \"umps1-sshare.*-sjl.ops.sfdc.net\"), \"SJL-SP1-C1\","
        + "match(host, \"umps2-sshare.*-sjl.ops.sfdc.net\"), \"SJL-SP1-C2\","
        + "match(host, \"umps1-sshare.*-asg.ops.sfdc.net\"), \"ASG-SP1-C1\","
        + "match(host, \"umps2-sshare.*-asg.ops.sfdc.net\"), \"ASG-SP1-C2\","
        + "match(host, \"umps1-sshare.*-chx.ops.sfdc.net\"), \"ASG-GOVT-C1\","
        + "match(host, \"umps1-sshare.*-wax.ops.sfdc.net\"), \"ASG-GOVT-C2\","
        + "match(host, \"umps1-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP1-C1\",   "
        + "match(host, \"umps2-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP1-C2\",   "
        + "match(host, \"umps3-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP1-C3\",   "
        + "match(host, \"umps4-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP1-C4\",   "
        + "match(host, \"umps1-sshare.*-was.ops.sfdc.net\"), \"WAS-SP1-C1\",   "
        + "match(host, \"umps2-sshare.*-was.ops.sfdc.net\"), \"WAS-SP1-C2\",   "
        + "match(host, \"umps3-sshare.*-was.ops.sfdc.net\"), \"WAS-SP1-C3\",   "
        + "match(host, \"umps4-sshare.*-was.ops.sfdc.net\"), \"WAS-SP1-C4\",   "
        + "match(host, \"umps1-sshare.*-tyo.ops.sfdc.net\"), \"TYO-SP1-C1\",   "
        + "match(host, \"umps2-sshare.*-tyo.ops.sfdc.net\"), \"TYO-SP1-C2\",   "
        + "match(host, \"umps3-sshare.*-tyo.ops.sfdc.net\"), \"TYO-SP1-C3\",   "
        + "match(host, \"umps4-sshare.*-tyo.ops.sfdc.net\"), \"TYO-SP1-C4\",   "
        + "match(host, \"umps20-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP2-C1\",  "
        + "match(host, \"umps21-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP2-C2\",   "
        + "match(host, \"umps22-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP2-C3\",   "
        + "match(host, \"umps23-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP2-C4\",   "
        + "match(host, \"umps20-sshare.*-was.ops.sfdc.net\"), \"WAS-SP2-C1\",   "
        + "match(host, \"umps21-sshare.*-was.ops.sfdc.net\"), \"WAS-SP2-C2\",   "
        + "match(host, \"umps22-sshare.*-was.ops.sfdc.net\"), \"WAS-SP2-C3\",   "
        + "match(host, \"umps23-sshare.*-was.ops.sfdc.net\"), \"WAS-SP2-C4\",   "
        + "match(host, \"umps30-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP3-C1\",   "
        + "match(host, \"umps31-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP3-C2\",   "
        + "match(host, \"umps32-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP3-C3\",   "
        + "match(host, \"umps33-sshare.*-chi.ops.sfdc.net\"), \"CHI-SP4-C4\",   "
        + "match(host, \"umps30-sshare.*-was.ops.sfdc.net\"), \"WAS-SP3-C1\",   "
        + "match(host, \"umps31-sshare.*-was.ops.sfdc.net\"), \"WAS-SP3-C2\",   "
        + "match(host, \"umps32-sshare.*-was.ops.sfdc.net\"), \"WAS-SP3-C3\",   "
        + "match(host, \"umps33-sshare.*-was.ops.sfdc.net\"), \"WAS-SP3-C4\",   "
        + "match(host, \".*\"), host)| fields instance _indextime | eval indextime=_indextime | fields - _raw "
        + "| stats min(indextime) as eTime by instance  | convert ctime(eTime)";
    
    
    String query2="search index=distapps  earliest=-60m@m sourcetype=CASE(liveagentserverV1:laope) |" 
        + "eval instance=case(match(host,\"la30-lapp1.*-chi.ops.sfdc.net\") OR match(host,\"la30-lapp2.*-chi.ops.sfdc.net\"),\"chi-3-1-Prod\","
        +"match(host,\"la21-cs1.*-chi.ops.sfdc.net\") OR match(host,\"la21-cs2.*-chi.ops.sfdc.net\"),\"chi-2-2-CS\","
        +"match(host,\"la1-cs1.*-sjl.ops.sfdc.net\") OR match(host,\"la1-cs2.*-sjl.ops.sfdc.net\"),\"sjl-1-1-CS\","
        +"match(host,\"la1-lapp1.*-tyo.ops.sfdc.net\") OR match(host,\"la1-lapp2.*-tyo.ops.sfdc.net\"),\"tyo-1-1-Prod\","
        +"match(host,\"la30-cs1.*-chi.ops.sfdc.net\") OR match(host,\"la30-cs2.*-chi.ops.sfdc.net\"),\"chi-3-1-CS\","
        +"match(host,\"la1-lapp1.*-sjl.ops.sfdc.net\") OR match(host,\"la1-lapp2.*-sjl.ops.sfdc.net\"),\"sjl-1-1-Prod\","
        +"match(host,\"la1-cs1.*-tyo.ops.sfdc.net\") OR match(host,\"la1-cs2.*-tyo.ops.sfdc.net\"),\"tyo-1-1-CS\","
        +"match(host,\"gla1-lapp.*-chi.ops.sfdc.net\"),\"chi-gus\","
        +"match(host,\"la1-lapp1.*-chi.ops.sfdc.net\") OR match(host,\"la1-lapp2.*-chi.ops.sfdc.net\"),\"chi-1-1-Prod\","
        +"match(host,\"la1-cs1.*-chi.ops.sfdc.net\") OR match(host,\"la1-cs2.*-chi.ops.sfdc.net\"),\"chi-1-1-CS\","
        +"match(host,\"la2-lapp1.*-chi.ops.sfdc.net\") OR match(host,\"la2-lapp2.*-chi.ops.sfdc.net\"),\"chi-1-2-Prod\","
        +"match(host,\"la2-cs1.*-chi.ops.sfdc.net\") OR match(host,\"la2-cs2.*-chi.ops.sfdc.net\"),\"chi-1-2-CS\","
        +"match(host,\"la20-lapp1.*-chi.ops.sfdc.net\") OR match(host,\"la20-lapp2.*-chi.ops.sfdc.net\"),\"chi-2-1-Prod\","
        +"match(host,\"la20-cs1.*-chi.ops.sfdc.net\") OR match(host,\"la20-cs2.*-chi.ops.sfdc.net\"),\"chi-2-1-CS\","
        +"match(host,\"la21-lapp1.*-chi.ops.sfdc.net\") OR match(host,\"la21-lapp2.*-chi.ops.sfdc.net\"),\"chi-2-2-Prod\","
        +"match(host,\"la2-lapp1.*-tyo.ops.sfdc.net\") OR match(host,\"la2-lapp2.*-tyo.ops.sfdc.net\"),\"tyo-1-2-Prod\","
        +"match(host,\"la2-cs1.*-tyo.ops.sfdc.net\") OR match(host,\"la2-cs2.*-tyo.ops.sfdc.net\"),\"tyo-1-2-CS\","
        +"match(host,\"la1-lapp1.*-was.ops.sfdc.net\") OR match(host,\"la1-lapp2.*-was.ops.sfdc.net\"),\"was-1-1-Prod\","
        +"match(host,\"la31-cs1.*-chi.ops.sfdc.net\") OR match(host,\"la31-cs2.*-chi.ops.sfdc.net\"),\"chi-3-2-CS\","
        +"match(host,\"la31-lapp1.*-chi.ops.sfdc.net\") OR match(host,\"la31-lapp2.*-chi.ops.sfdc.net\"),\"chi-3-2-Prod\","
        +"match(host,\"la2-lapp1.*-was.ops.sfdc.net\") OR match(host,\"la2-lapp2.*-was.ops.sfdc.net\"),\"was-1-2-Prod\","
        +"match(host,\"la20-lapp1.*-was.ops.sfdc.net\") OR match(host,\"la20-lapp2.*-was.ops.sfdc.net\"),\"was-2-1-Prod\","
        +"match(host,\"la21-lapp1.*-was.ops.sfdc.net\") OR match(host,\"la21-lapp2.*-was.ops.sfdc.net\"),\"was-2-2-Prod\","
        +"match(host,\"la30-lapp1.*-was.ops.sfdc.net\") OR match(host,\"la30-lapp2.*-was.ops.sfdc.net\"),\"was-3-1-Prod\","
        +"match(host,\"la31-lapp1.*-was.ops.sfdc.net\") OR match(host,\"la31-lapp2.*-was.ops.sfdc.net\"),\"was-3-2-Prod\","
        +"match(host,\"la1-cs1.*-was.ops.sfdc.net\") OR match(host,\"la1-cs2.*-was.ops.sfdc.net\"),\"was-1-1-CS\","
        +"match(host,\"la2-cs1.*-was.ops.sfdc.net\") OR match(host,\"la2-cs2.*-was.ops.sfdc.net\"),\"was-1-2-CS\","
        +"match(host,\"la20-cs1.*-was.ops.sfdc.net\") OR match(host,\"la20-cs2.*-was.ops.sfdc.net\"),\"was-2-1-CS\","
        +"match(host,\"la21-cs1.*-was.ops.sfdc.net\") OR match(host,\"la21-cs2.*-was.ops.sfdc.net\"),\"was-2-2-CS\","
        +"match(host,\"la30-cs1.*-was.ops.sfdc.net\") OR match(host,\"la30-cs2.*-was.ops.sfdc.net\"),\"was-3-1-CS\","
        +"match(host,\"la31-cs1.*-was.ops.sfdc.net\") OR match(host,\"la31-cs2.*-was.ops.sfdc.net\"),\"was-3-2-CS\","
        +"match(host,\"la1-lapp1.*-asg.ops.sfdc.net\") OR match(host,\"la1-lapp2.*-asg.ops.sfdc.net\"),\"asg-1-1-Prod\","
        +"match(host,\"la1-cs1.*-asg.ops.sfdc.net\") OR match(host,\"la1-cs2.*-asg.ops.sfdc.net\"),\"asg-1-1-CS\","
        +"match(host, \".*\"), host)| fields instance _indextime | eval indextime=_indextime | fields - _raw "
        +"| stats min(indextime) as eTime by instance  | convert ctime(eTime) ";
    System.out.println(query2);
  }
  


}
